=== Learn0/spring-boot-web-project/src/main/resources/static/xml/area.dtd
<!ELEMENT total (area+)>
<!ELEMENT area (area_nm,borough_nm)>
<!ELEMENT area_nm (#PCDATA)>
<!ELEMENT borough_nm (#PCDATA)>
<!ATTLIST area name CDATA "" borough CDATA "">

=== Learn0/spring-boot-web-project/src/main/resources/static/xml/area.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE total SYSTEM "area.dtd">
<total>
	<area name="test_area" borough="test_borough">
		<area_nm>서울특별시</area_nm>
		<borough_nm>강남구</borough_nm>
	</area>
	<area name="test_area" borough="test_borough">
		<area_nm>서울특별시</area_nm>
		<borough_nm>강동구</borough_nm>
	</area>
	<area name="test_area" borough="test_borough">
		<area_nm>서울특별시</area_nm>
		<borough_nm>강북구</borough_nm>
	</area>
	<area name="test_area" borough="test_borough">
		<area_nm>서울특별시</area_nm>
		<borough_nm>강서구</borough_nm>
	</area>
	<area name="test_area" borough="test_borough">
		<area_nm>서울특별시</area_nm>
		<borough_nm>관악구</borough_nm>
	</area>
	<area name="test_area" borough="test_borough">
		<area_nm>서울특별시</area_nm>
		<borough_nm>광진구</borough_nm>
	</area>
	<area name="test_area" borough="test_borough">
		<area_nm>서울특별시</area_nm>
		<borough_nm>구로구</borough_nm>
	</area>
	<area name="test_area" borough="test_borough">
		<area_nm>서울특별시</area_nm>
		<borough_nm>금천구</borough_nm>
	</area>
	<area name="test_area" borough="test_borough">
		<area_nm>서울특별시</area_nm>
		<borough_nm>노원구</borough_nm>
	</area>
	<area name="test_area" borough="test_borough">
		<area_nm>서울특별시</area_nm>
		<borough_nm>도봉구</borough_nm>
	</area>
	<area name="test_area" borough="test_borough">
		<area_nm>서울특별시</area_nm>
		<borough_nm>동대문구</borough_nm>
	</area>
	<area name="test_area" borough="test_borough">
		<area_nm>서울특별시</area_nm>
		<borough_nm>동작구</borough_nm>
	</area>
	<area name="test_area" borough="test_borough">
		<area_nm>서울특별시</area_nm>
		<borough_nm>마포구</borough_nm>
	</area>
	<area name="test_area" borough="test_borough">
		<area_nm>서울특별시</area_nm>
		<borough_nm>서대문구</borough_nm>
	</area>
	<area name="test_area" borough="test_borough">
		<area_nm>서울특별시</area_nm>
		<borough_nm>서초구</borough_nm>
	</area>
	<area name="test_area" borough="test_borough">
		<area_nm>서울특별시</area_nm>
		<borough_nm>성동구</borough_nm>
	</area>
	<area name="test_area" borough="test_borough">
		<area_nm>서울특별시</area_nm>
		<borough_nm>성북구</borough_nm>
	</area>
	<area name="test_area" borough="test_borough">
		<area_nm>서울특별시</area_nm>
		<borough_nm>송파구</borough_nm>
	</area>
	<area name="test_area" borough="test_borough">
		<area_nm>서울특별시</area_nm>
		<borough_nm>양천구</borough_nm>
	</area>
	<area name="test_area" borough="test_borough">
		<area_nm>서울특별시</area_nm>
		<borough_nm>영등포구</borough_nm>
	</area>
	<area name="test_area" borough="test_borough">
		<area_nm>서울특별시</area_nm>
		<borough_nm>용산구</borough_nm>
	</area>
	<area name="test_area" borough="test_borough">
		<area_nm>서울특별시</area_nm>
		<borough_nm>은평구</borough_nm>
	</area>
	<area name="test_area" borough="test_borough">
		<area_nm>서울특별시</area_nm>
		<borough_nm>종로구</borough_nm>
	</area>
	<area name="test_area" borough="test_borough">
		<area_nm>서울특별시</area_nm>
		<borough_nm>중구</borough_nm>
	</area>
	<area name="test_area" borough="test_borough">
		<area_nm>서울특별시</area_nm>
		<borough_nm>중랑구</borough_nm>
	</area>
	<area name="test_area" borough="test_borough">
		<area_nm>부산광역시</area_nm>
		<borough_nm>강서구</borough_nm>
	</area>
	<area name="test_area" borough="test_borough">
		<area_nm>부산광역시</area_nm>
		<borough_nm>금정구</borough_nm>
	</area>
	<area name="test_area" borough="test_borough">
		<area_nm>부산광역시</area_nm>
		<borough_nm>기장군</borough_nm>
	</area>
	<area name="test_area" borough="test_borough">
		<area_nm>부산광역시</area_nm>
		<borough_nm>남구</borough_nm>
	</area>
	<area name="test_area" borough="test_borough">
		<area_nm>부산광역시</area_nm>
		<borough_nm>동구</borough_nm>
	</area>
	<area name="test_area" borough="test_borough">
		<area_nm>부산광역시</area_nm>
		<borough_nm>동래구</borough_nm>
	</area>
	<area name="test_area" borough="test_borough">
		<area_nm>부산광역시</area_nm>
		<borough_nm>부산진구</borough_nm>
	</area>
	<area name="test_area" borough="test_borough">
		<area_nm>부산광역시</area_nm>
		<borough_nm>북구</borough_nm>
	</area>
	<area name="test_area" borough="test_borough">
		<area_nm>부산광역시</area_nm>
		<borough_nm>사상구</borough_nm>
	</area>
	<area name="test_area" borough="test_borough">
		<area_nm>부산광역시</area_nm>
		<borough_nm>사하구</borough_nm>
	</area>
	<area name="test_area" borough="test_borough">
		<area_nm>부산광역시</area_nm>
		<borough_nm>서구</borough_nm>
	</area>
	<area name="test_area" borough="test_borough">
		<area_nm>부산광역시</area_nm>
		<borough_nm>수영구</borough_nm>
	</area>
	<area name="test_area" borough="test_borough">
		<area_nm>부산광역시</area_nm>
		<borough_nm>연제구</borough_nm>
	</area>
	<area name="test_area" borough="test_borough">
		<area_nm>부산광역시</area_nm>
		<borough_nm>영도구</borough_nm>
	</area>
	<area name="test_area" borough="test_borough">
		<area_nm>부산광역시</area_nm>
		<borough_nm>중구</borough_nm>
	</area>
	<area name="test_area" borough="test_borough">
		<area_nm>부산광역시</area_nm>
		<borough_nm>해운대구</borough_nm>
	</area>
	<area name="test_area" borough="test_borough">
		<area_nm>대구광역시</area_nm>
		<borough_nm>남구</borough_nm>
	</area>
	<area name="test_area" borough="test_borough">
		<area_nm>대구광역시</area_nm>
		<borough_nm>달서구</borough_nm>
	</area>
	<area name="test_area" borough="test_borough">
		<area_nm>대구광역시</area_nm>
		<borough_nm>달성군</borough_nm>
	</area>
	<area name="test_area" borough="test_borough">
		<area_nm>대구광역시</area_nm>
		<borough_nm>동구</borough_nm>
	</area>
	<area name="test_area" borough="test_borough">
		<area_nm>대구광역시</area_nm>
		<borough_nm>북구</borough_nm>
	</area>
	<area name="test_area" borough="test_borough">
		<area_nm>대구광역시</area_nm>
		<borough_nm>서구</borough_nm>
	</area>
	<area name="test_area" borough="test_borough">
		<area_nm>대구광역시</area_nm>
		<borough_nm>수성구</borough_nm>
	</area>
	<area name="test_area" borough="test_borough">
		<area_nm>대구광역시</area_nm>
		<borough_nm>중구</borough_nm>
	</area>
	<area name="test_area" borough="test_borough">
		<area_nm>인천광역시</area_nm>
		<borough_nm>강화군</borough_nm>
	</area>
	<area name="test_area" borough="test_borough">
		<area_nm>인천광역시</area_nm>
		<borough_nm>계양구</borough_nm>
	</area>
	<area name="test_area" borough="test_borough">
		<area_nm>인천광역시</area_nm>
		<borough_nm>남동구</borough_nm>
	</area>
	<area name="test_area" borough="test_borough">
		<area_nm>인천광역시</area_nm>
		<borough_nm>동구</borough_nm>
	</area>
	<area name="test_area" borough="test_borough">
		<area_nm>인천광역시</area_nm>
		<borough_nm>미추홀구</borough_nm>
	</area>
	<area name="test_area" borough="test_borough">
		<area_nm>인천광역시</area_nm>
		<borough_nm>부평구</borough_nm>
	</area>
	<area name="test_area" borough="test_borough">
		<area_nm>인천광역시</area_nm>
		<borough_nm>서구</borough_nm>
	</area>
	<area name="test_area" borough="test_borough">
		<area_nm>인천광역시</area_nm>
		<borough_nm>연수구</borough_nm>
	</area>
	<area name="test_area" borough="test_borough">
		<area_nm>인천광역시</area_nm>
		<borough_nm>옹진군</borough_nm>
	</area>
	<area name="test_area" borough="test_borough">
		<area_nm>인천광역시</area_nm>
		<borough_nm>중구</borough_nm>
	</area>
	<area name="test_area" borough="test_borough">
		<area_nm>광주광역시</area_nm>
		<borough_nm>광산구</borough_nm>
	</area>
	<area name="test_area" borough="test_borough">
		<area_nm>광주광역시</area_nm>
		<borough_nm>남구</borough_nm>
	</area>
	<area name="test_area" borough="test_borough">
		<area_nm>광주광역시</area_nm>
		<borough_nm>동구</borough_nm>
	</area>
	<area name="test_area" borough="test_borough">
		<area_nm>광주광역시</area_nm>
		<borough_nm>북구</borough_nm>
	</area>
	<area name="test_area" borough="test_borough">
		<area_nm>광주광역시</area_nm>
		<borough_nm>서구</borough_nm>
	</area>
	<area name="test_area" borough="test_borough">
		<area_nm>대전광역시</area_nm>
		<borough_nm>대덕구</borough_nm>
	</area>
	<area name="test_area" borough="test_borough">
		<area_nm>대전광역시</area_nm>
		<borough_nm>동구</borough_nm>
	</area>
	<area name="test_area" borough="test_borough">
		<area_nm>대전광역시</area_nm>
		<borough_nm>서구</borough_nm>
	</area>
	<area name="test_area" borough="test_borough">
		<area_nm>대전광역시</area_nm>
		<borough_nm>유성구</borough_nm>
	</area>
	<area name="test_area" borough="test_borough">
		<area_nm>대전광역시</area_nm>
		<borough_nm>중구</borough_nm>
	</area>
	<area name="test_area" borough="test_borough">
		<area_nm>울산광역시</area_nm>
		<borough_nm>남구</borough_nm>
	</area>
	<area name="test_area" borough="test_borough">
		<area_nm>울산광역시</area_nm>
		<borough_nm>동구</borough_nm>
	</area>
	<area name="test_area" borough="test_borough">
		<area_nm>울산광역시</area_nm>
		<borough_nm>북구</borough_nm>
	</area>
	<area name="test_area" borough="test_borough">
		<area_nm>울산광역시</area_nm>
		<borough_nm>울주군</borough_nm>
	</area>
	<area name="test_area" borough="test_borough">
		<area_nm>울산광역시</area_nm>
		<borough_nm>중구</borough_nm>
	</area>
	<area name="test_area" borough="test_borough">
		<area_nm>세종특별자치시</area_nm>
		<borough_nm>세종특별자치시</borough_nm>
	</area>
	<area name="test_area" borough="test_borough">
		<area_nm>경기도</area_nm>
		<borough_nm>가평군</borough_nm>
	</area>
	<area name="test_area" borough="test_borough">
		<area_nm>경기도</area_nm>
		<borough_nm>고양시</borough_nm>
	</area>
	<area name="test_area" borough="test_borough">
		<area_nm>경기도</area_nm>
		<borough_nm>과천시</borough_nm>
	</area>
	<area name="test_area" borough="test_borough">
		<area_nm>경기도</area_nm>
		<borough_nm>광명시</borough_nm>
	</area>
	<area name="test_area" borough="test_borough">
		<area_nm>경기도</area_nm>
		<borough_nm>광주시</borough_nm>
	</area>
	<area name="test_area" borough="test_borough">
		<area_nm>경기도</area_nm>
		<borough_nm>구리시</borough_nm>
	</area>
	<area name="test_area" borough="test_borough">
		<area_nm>경기도</area_nm>
		<borough_nm>군포시</borough_nm>
	</area>
	<area name="test_area" borough="test_borough">
		<area_nm>경기도</area_nm>
		<borough_nm>김포시</borough_nm>
	</area>
	<area name="test_area" borough="test_borough">
		<area_nm>경기도</area_nm>
		<borough_nm>남양주시</borough_nm>
	</area>
	<area name="test_area" borough="test_borough">
		<area_nm>경기도</area_nm>
		<borough_nm>동두천시</borough_nm>
	</area>
	<area name="test_area" borough="test_borough">
		<area_nm>경기도</area_nm>
		<borough_nm>부천시</borough_nm>
	</area>
	<area name="test_area" borough="test_borough">
